version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    allow:
      - dependency-name: "szepeviktor/phpstan-wordpress"
      - dependency-name: "squizlabs/php_codesniffer"
      - dependency-name: "phpunit/phpunit"
      - dependency-name: "10up/wp_mock"

  - package-ecosystem: "pip"
    directory: "/testing"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
